# .readthedocs.yml
version: 2

# 设置构建的Python版本
python:
  version: 3.8 # 根据你的项目需求选择合适的Python版本

# 安装要求，这里列出需要通过pip安装的所有依赖
install:
  - pip install -r requirements.txt # 假设你的项目有一个requirements.txt文件列出了所有依赖
  - pip install sphinx_rtd_theme # 明确指定安装sphinx_rtd_theme

# 构建配置
sphinx:
  configuration: docs/source/conf.py # 指向你的Sphinx配置文件路径