version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
    jobs:
      pre_create_environment:
        pip install sphinx_rtd_theme
sphinx:
   configuration: docs/source/conf.py  # sphinx配置文件路径