# .readthedocs.yml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    pre_install:
     - pip install sphinx_rtd_theme

# 构建配置
sphinx:
  configuration: docs/source/conf.py # 指向你的Sphinx配置文件路径